version: "3.7"
services:

 redis:
    image: redis:6.2.4-alpine
    command: redis-server --appendonly yes
    ports:
     - 6379:6379
    volumes:
      - $PWD/data:/data
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    restart: unless-stopped
    networks:
      - suit-network

networks:
  suit-network:
    external: true